name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          find . -type 'f' | grep -v ".git" | grep -v "public" | xargs rm
          find . -type 'd' | grep -v ".git" | grep -v "public" | xargs rm -rf || echo "Good"
          mv public/* .
          rm -rf ./public
        shell: bash
      - name: Commit report
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -am "Automatic Deploy action run by github-actions"
          git push origin HEAD:gh-pages --force

      #- run: git config --local user.name github-actions
      #  shell: bash
      #- run: git config --local user.email github-actions@github.com
      #  shell: bash
      #- run : git commit -m "Automatic Deploy action run by github-actions" -a
      #  shell: bash
      #- run : git push origin HEAD:gh-pages --force
      #  shell: bash