name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node 16
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
        shell: bash
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
          ls -l
        shell: bash
      - name: Extract build
        run: |
          ls -l
          find . -type 'f' | grep -v ".git" | grep -v "public" | xargs rm
          find . -type 'd' | grep -v ".git" | grep -v "public" | xargs rm -rf || echo "Good"
          mv build/* .
          sudo rm -rf ./build
          echo "ltvcac.agency" > CNAME
        shell: bash
      - name: Commit
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -am "Automatic Deploy action run by github-actions"
          git push origin HEAD:gh-pages --force
