name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: find . -type 'f' | grep -v ".git" | grep -v "public" | xargs rm
        shell: bash
      - run: ls -l
        shell: bash
      - run: find . -type 'd' | grep -v ".git" | grep -v "public" | xargs rm -rf || echo "Good"
        shell: bash
      - run: ls -l
        shell: bash
      - run: mv public/* .
        shell: bash
      - run: ls -l
        shell: bash
      - run: rm -rf ./public
        shell: bash
      - run: git config --local user.name github-actions
        shell: bash
      - run: git config --local user.email github-actions@github.com
        shell: bash
      - run : git commit -m "Automatic Deploy action run by github-actions" -a
        shell: bash
      - run : git push origin HEAD:gh-pages --force
        shell: bash